import React from "react";
import {
  Icon,
  Row,
  Card,
  CardTitle,
  Col,
  Divider,
  Carousel,
} from "react-materialize";
import QHouseExtrasSauna from "../SVG/QHouseExtrasSauna.svg";
import QHouseExtrasGarageFlat from "../SVG/QHouseExtrasGarageFlat.svg";
import QHouseExtrasGaragePitched from "../SVG/QHouseExtrasGaragePitched.svg";
import QHouseExtrasOutdoorKitchen from "../SVG/QHouseExtrasOutdoorKitchen.svg";
import QHouseExtrasSwimmingPool from "../SVG/QHouseExtrasSwimmingPool.svg";
import QHouseExtrasShedFlat from "../SVG/QHouseExtrasShedFlat.svg";
import QHouseExtrasShedPitched from "../SVG/QHouseExtrasShedPitched.svg";
import garageFlat from "../SVG/garagplaski.png";
import garagePitched from "../SVG/garazdwuspadowy.png";

let baseUrl =
  "https://raw.githubusercontent.com/galeriapodsloncem/3dstrona/master/babylonjs-app/public/assets/zdjeciakonfigurator/";

const ResourcesAddons = [
 
  {
    plname: "Garaż Dach Płaski",
    enname: "Garage Flat Roof",
    pldescription:
      "Istnieje możliwość zamówienia podwójnego garażu. Jego konstrukcja jest zbliżona do specyfikacji domu z drewnianymi ścianami i dachem z blachy ocynkowanej. Szerokość 6,7 mi głębokość 6,8 m pozwalają zmieścić 2 duże samochody, kilka rowerów oraz sprzęt typu kosiarka. Na piętrze znajduje się antresola.",
    endescription: "It is possible to order a double garage. Its structure is similar to the specification of a house with wooden walls and a roof made of galvanized steel sheet. The width of 6.7 m and the depth of 6.8 m allow you to fit 2 large cars, a few bicycles and a lawn mower. mezzanine with an area of ​​39 m2. ",
    video: "https://youtu.be/0St5oMHzXRQ",
    rysunki: QHouseExtrasGarageFlat,

    plspecification: [
      <h5>35m2</h5>,
      "2 miejsca parkingowe",
      <Divider />,
      <br />,
      "Dostępne rózne wersje wykończenia",
      <Divider />,
      <br />,
      "Parter miejsce na: 2 samochody, rower, kosiarkę, narzędzia",
      <Divider />,
      <br />,
      "Budynek Wolnostojący, docieplenie doestępne za dopłatą",
      <Divider />,
    ],
    enspecification: [
      <h5>35m2</h5>,
      "2 parking spaces",
      <Divider />,
      <br />,

      "Various finishes available",
      <Divider />,
      <br />,
      "Ground floor space for: 2 cars, bicycle, mower, tools",
      <Divider />,
      <br />,

      "Detached building, thermal insulation optional",
      <Divider />,
    ],
    pdf: "zxfzczx",
    img1: garageFlat,
    img2: baseUrl + "GarageFlat/Image%2004.png",
    img3: baseUrl + "GarageFlat/Image%2005.png",
    img4: baseUrl + "GarageFlat/Image%2006.png",
  },
  {
    plname: "Garaż Dach Dwuspadowy",
    enname: "Garage Pitched Roof",
    pldescription:
      "Istnieje możliwość zamówienia podwójnego garażu. Jego konstrukcja jest zbliżona do specyfikacji domu z drewnianymi ścianami i dachem z blachy malowanej. Szerokość 6,7 mi głębokość 6,8 m pozwalają zmieścić 2 duże samochody, kilka rowerów oraz sprzęt typu kosiarka. Na piętrze znajduje się antresola.",
    endescription: "It is possible to order a double garage. Its structure is similar to the specification of a house with wooden walls and a painted sheet roof. The width of 6.7 m and the depth of 6.8 m allow you to fit 2 large cars, a few bicycles and mower-type equipment. mezzanine with an area of ​​39 m2. ",
    video: "https://youtu.be/Mw1FJalhfBg",
    rysunki: QHouseExtrasGaragePitched,

    plspecification: [
      <h5>35mm2</h5>,
      "2 miejsca parkingowe",
      <Divider />,
      <br />,
      "Antresola",
      <Divider />,
      <br />,
      "Dostępne rózne wersje wykończenia",
      <Divider />,
      <br />,
      "Parter miejsce na: 2 samochody, rower, kosiarkę, narzędzia",
      <Divider />,
      <br />,
      "Antresola miejsce na: przechowywanie, narzędzia",
      <Divider />,
      <br />,
      "Budynek Wolnostojący, docieplenie doestępne za dopłatą",
      <Divider />,
    ],
    enspecification: [
      <h5>35m2</h5>,
      "2 parking spaces",
      <Divider />,
      <br />,
      "Mezzanine",
      <Divider />,
      <br />,
      "Various finishes available",
      <Divider />,
      <br />,
      "Ground floor space for: 2 cars, bicycle, mower, tools",
      <Divider />,
      <br />,
      "Mezzanine space for: storage, woring space, tools",
      <Divider />,
      <br />,
      "Detached building",
      <Divider />,
    ],
    pdf: "zxfzczx",
    img1: garagePitched,
    img2: baseUrl + "GaragePitched/Image%2008.png",
    img3: baseUrl + "GaragePitched/Image%2007.png",
    img4: baseUrl + "GaragePitched/Image%20010.png",
  },
  {
    plname: "Wiata Dach Pochylony",
    enname: "Shed Sloping Roof",
    pldescription: "Oferujemy możliwość zamówienie wiaty wykonanej z drewna. Wiata montowana jest przed wejscien do domu i daje schronienie dla 2 samochodów i 2 rowerów",
    endescription: "We offer the possibility to order a carport made of wood. The carport is installed in front of the entrance to the house and provides shelter for 2 cars and 2 bicycles",
    video: "https://youtu.be/ru7O5LK4jVI",
    rysunki: QHouseExtrasShedPitched,
    plspecification: [
      // <h5>?m2</h5>,
      "2 miejsca parkingowe",
      <Divider />,
      <br />,
      "Miejsce na: 2 samochody, rowery, motocykl",
      <Divider />,
    ],
    enspecification: [
      
      "2 parking spaces",
      <Divider />,
      <br />,
      "Space for: 2 cars, bicycle, motocycle",
      <Divider />,
    ],
    pdf: "zxfzczx",
    img1: baseUrl + "WiataSpadek/Image%2002.png",
    img2: baseUrl + "WiataSpadek/Image%2001.png",
    img3: baseUrl + "WiataSpadek/Image%2003.png",
    img4: baseUrl + "WiataSpadek/Image%2004.png",
  },
  {
    plname: "Wiata Dach Płaski",
    enname: "Shed Flat Roof",
    pldescription: "Oferujemy możliwość zamówienie wiaty wykonanej z drewna. Wiata montowana jest przed wejscien do domu i daje schronienie dla 2 samochodów i 2 rowerów",
    endescription: "We offer the possibility to order a carport made of wood. The carport is installed in front of the entrance to the house and provides shelter for 2 cars and 2 bicycles",
    video: "https://youtu.be/wyiLqDKZQPw",
    rysunki: QHouseExtrasShedFlat,
    plspecification: [
      
      "2 miejsca parkingowe",
      <Divider />,
      <br />,

      "Parter miejsce na: 2 samochody, rower, motocykl",
      <Divider />,
    ],
    enspecification: [
      // <h5>?m2</h5>,
      "2 parking spaces",
      <Divider />,
      <br />,
      "Space for: 2 cars, bicycle, motocycle",
      <Divider />,
    ],
    pdf: "zxfzczx",
    img1: baseUrl + "WiataPlaska/Image%2003.png",
    img2: baseUrl + "WiataPlaska/Image%2004.png",
    img3: baseUrl + "WiataPlaska/Image%2005.png",
    img4: baseUrl + "WiataPlaska/Image%2006.png",
  },
  {
    plname: "Kuchnia Na Świeżym Powietrzu",
    enname: "Outdoor Kitchen",
    pldescription:
      "Kuchnia na świeżym powietrzu to idealna propozycja dla kochających gotować w otoczeniu matki natury. Wielkość kuchni pozwala na wygodne przygotowanie posiłków, i przyjmowanie gości pod dachem. Projekt skupia się na zapewnia schronienie przed żywiołami i nie zasłania widoków. Struktura jest wykonana z drewna.",
    endescription: "The open-air kitchen is an ideal proposition for those who love to cook surrounded by mother nature. The size of the kitchen allows you to conveniently prepare meals and receive guests indoors. The project focuses on providing shelter from the elements and does not obstruct the view. The structure is made of wood." ,
    video: "https://youtu.be/SM-UN8tmYK8",
    rysunki: QHouseExtrasOutdoorKitchen,
    plspecification: [
      
      // "2 miejsca parkingowe",
      // <Divider />,
      // <br />,
      // "Antresola",
      // <Divider />,
      // <br />,
      // "Dostępne rózne wersje wykończenia",
      // <Divider />,
      // <br />,
      // "Parter miejsce na: 2 samochody, rower, kosiarkę, narzędzia",
      // <Divider />,
      // <br />,
      // "Antresola miejsce na: przechowywanie, narzędzia",
      // <Divider />,
      // <br />,
      // "Budynek Wolnostojący",
      // <Divider />,
    ],
    enspecification: [
      // "1. salon m2",
      // "2. kuchnia m2",
      // "1a. lub salon z aneksem kuchennym m2",
      // "3. łazienka m2",
      // "4. wc m2",
      // "5. przedsionek m2",
      // "6. hol m2",
      // "7. pokój 1 z garderobą",
      // "8. pokój 2",
      // "9. pokój 3",
      // "10. pokój 4",
      // "11. poddasze",
    ],
    pdf: "zxfzczx",
    img1: baseUrl + "Kitchen/Image%2011.png",
    img2: baseUrl + "Kitchen/Image%2012.png",
    img3: baseUrl + "Kitchen/Image%2005.png",
    img4: baseUrl + "Kitchen/Image%2006.png",
  },
  {
    plname: "Basen Niemiecki",
    enname: "Swimming Pool",
    pldescription: "Niecka basenu została wykonana z paneli stalowych SteelPrime o grubości 2 mm. Panele pokryte są podwójną warstwą galwaniczną cynku i aluminium 750/800 g/m2 oraz opatentowaną warstwą magnezu Spectron. Dzięki takiej formule panele odporne są na korozję nawet do 25 lat, Panele są wytwarzane w pełni zautomatyzowanej technice, dlatego są dziesięciokrotnie silniejsze i trwalsze niż te wytwarzane tradycyjną metodą. Dodatkowo warstwa Spectron, w której panel zanurzany jest kilkakrotnie, zabezpiecza je przed działaniem chemikaliów tj. chlorki i związki amoniaku, a także przed oddziaływaniem soli oraz procesu utleniania; Panele przeszły rygorystyczne testy, zgodne z normami: ISSO 3497, EN2808, EN 9227 oraz EN ISSO ISSO 4628;",
    endescription: "The basin of the pool is made of SteelPrime 2 mm thick steel panels. The panels are covered with a double galvanic layer of zinc and aluminum 750/800 g / m2 and the patented Spectron magnesium layer. Thanks to this formula, the panels are resistant to corrosion for up to 25 years. produced in a fully automated technique, therefore they are ten times stronger and more durable than those produced by the traditional method. Additionally, the Spectron layer, in which the panel is submerged several times, protects them against the effects of chemicals such as chlorides and ammonia compounds, as well as against the effects of salt and the oxidation process; The panels have passed rigorous tests in accordance with the following standards: ISSO 3497, EN2808, EN 9227 and EN ISSO ISSO 4628; ",
    video: "https://youtu.be/ru7O5LK4jVI",
    rysunki: QHouseExtrasSwimmingPool,
    plspecification: [
      // <h5>32m2</h5>,
      // "2 miejsca parkingowe",
      // <Divider />,
      // <br />,
      // "Antresola",
      // <Divider />,
      // <br />,
      // "Dostępne rózne wersje wykończenia",
      // <Divider />,
      // <br />,
      // "Parter miejsce na: 2 samochody, rower, kosiarkę, narzędzia",
      // <Divider />,
      // <br />,
      // "Antresola miejsce na: przechowywanie, narzędzia",
      // <Divider />,
      // <br />,
      // "Budynek Wolnostojący",
      // <Divider />,
    ],
    enspecification: [
      // "1. salon m2",
      // "2. kuchnia m2",
      // "1a. lub salon z aneksem kuchennym m2",
      // "3. łazienka m2",
      // "4. wc m2",
      // "5. przedsionek m2",
      // "6. hol m2",
      // "7. pokój 1 z garderobą",
      // "8. pokój 2",
      // "9. pokój 3",
      // "10. pokój 4",
      // "11. poddasze",
    ],
    pdf: "zxfzczx",
    img1:
      "https://a.allegroimg.com/s512/03f25a/28725e644ba2af9c22df376aa0b5/Basen-niemiecki-5-25x3-2x1-5m-MONTAZ-akcesoria",
    img2: baseUrl + "GarageFlat/Image%2004.png",
    img3: baseUrl + "GarageFlat/Image%2005.png",
    img4: baseUrl + "GarageFlat/Image%2006.png",
  },

  {
    plname: "Sauna ogrodowa ",
    enname: "Outdoor sauna ",
    pldescription: "Domek saunowy to rewelacyjne rozwiązanie dla tych, którzy pragną doświadczyć jedynego w swoim rodzaju odpoczynku na łonie natury. Ogród otaczający saunę ogrodową znacznie dodaje jej atrakcyjności. Zmieniająca się wraz z porami roku roślinność gwarantuje niepowtarzalne doznania podczas kąpieli parowej.",
    endescription: "The sauna house is a great solution for those who want to experience one-of-a-kind relaxation in the bosom of nature. The garden surrounding the garden sauna significantly adds to its attractiveness. The vegetation that changes with the seasons guarantees a unique experience during a steam bath.",
    video: "https://youtu.be/ru7O5LK4jVI",
    rysunki: QHouseExtrasSauna,
    plspecification: [
      // <h5>45m2</h5>,
      // "2 miejsca parkingowe",
      // <Divider />,
      // <br />,
      // "Antresola",
      // <Divider />,
      // <br />,
      // "Dostępne rózne wersje wykończenia",
      // <Divider />,
      // <br />,
      // "Parter miejsce na: 2 samochody, rower, kosiarkę, narzędzia",
      // <Divider />,
      // <br />,
      // "Antresola miejsce na: przechowywanie, narzędzia",
      // <Divider />,
      // <br />,
      // "Budynek Wolnostojący",
      // <Divider />,
    ],
    enspecification: [
      // "1. salon m2",
      // "2. kuchnia m2",
      // "1a. lub salon z aneksem kuchennym m2",
      // "3. łazienka m2",
      // "4. wc m2",
      // "5. przedsionek m2",
      // "6. hol m2",
      // "7. pokój 1 z garderobą",
      // "8. pokój 2",
      // "9. pokój 3",
      // "10. pokój 4",
      // "11. poddasze",
    ],
    //https://www.tapis.pl/sauny/sauny-ogrodowe/
    pdf: "zxfzczx",
    img1: "https://www.tapis.pl/sauny/sauny-ogrodowe/foto/crux-1.jpg",
    img2: baseUrl + "GarageFlat/Image%2004.png",
    img3: baseUrl + "GarageFlat/Image%2005.png",
    img4: baseUrl + "GarageFlat/Image%2006.png",
  },
  {
    plname: "Szklarnia przydomowa",
    enname: " Green House",
    pldescription: "Mało przydomowa szklarnia, idealna dla osób kochających świeże warzywa i zioła.",
    endescription:"A small home greenhouse, perfect for people who love fresh vegetables and herbs.",
    video: "https://youtu.be/ru7O5LK4jVI",
    rysunki: {},
    plspecification: [
      
      // "2 miejsca parkingowe",
      // <Divider />,
      // <br />,
      // "Antresola",
      // <Divider />,
      // <br />,
      // "Dostępne rózne wersje wykończenia",
      // <Divider />,
      // <br />,
      // "Parter miejsce na: 2 samochody, rower, kosiarkę, narzędzia",
      // <Divider />,
      // <br />,
      // "Antresola miejsce na: przechowywanie, narzędzia",
      // <Divider />,
      // <br />,
      // "Budynek Wolnostojący",
      // <Divider />,
    ],
    enspecification: [
      // "1. salon m2",
      // "2. kuchnia m2",
      // "1a. lub salon z aneksem kuchennym m2",
      // "3. łazienka m2",
      // "4. wc m2",
      // "5. przedsionek m2",
      // "6. hol m2",
      // "7. pokój 1 z garderobą",
      // "8. pokój 2",
      // "9. pokój 3",
      // "10. pokój 4",
      // "11. poddasze",
    ],
    //https://www.tapis.pl/sauny/sauny-ogrodowe/
    pdf: "zxfzczx",
    img1:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3O2eGojUu5MIElAHePCph27pB8spZypEtLQ&usqp=CAU",
    img2: baseUrl + "GarageFlat/Image%2004.png",
    img3: baseUrl + "GarageFlat/Image%2005.png",
    img4: baseUrl + "GarageFlat/Image%2006.png",
  },
];
export default ResourcesAddons;
